# Generated by Django 6.0.2 on 2026-04-27 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_organisation_invitationtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitationtoken",
            name="invited_for_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUPERADMIN", "Superadmin"),
                    ("ORG_ADMIN", "Org Admin"),
                    ("STAFF_ADMIN", "Staff Admin"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invitationtoken",
            name="purpose",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ORG_ADMIN", "Org Admin Setup"),
                    ("TEAM_MEMBER", "Team Member Invitation"),
                ],
                db_index=True,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="invited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invited_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
