# Generated by Django 6.0.2 on 2026-04-27 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_invitationtoken_v02"),
        ("regions", "0001_initial"),
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffAccessScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope_type",
                    models.CharField(
                        choices=[("REGION", "Region"), ("SHOP", "Shop")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_scopes",
                        to="regions.region",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_scopes",
                        to="shops.shop",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"role": "STAFF_ADMIN"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_scopes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_staff_access_scope",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "scope_type"], name="staff_scope_user_type_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("region__isnull", False),
                                ("scope_type", "REGION"),
                                ("shop__isnull", True),
                            ),
                            models.Q(
                                ("region__isnull", True),
                                ("scope_type", "SHOP"),
                                ("shop__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="staff_scope_xor_region_shop",
                    )
                ],
            },
        ),
    ]
