# Generated by Django 6.0.2 on 2026-05-02 14:26

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        ('reviews', '0004_review_extracted_action_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('input_token_price_per_1m', models.DecimalField(decimal_places=8, max_digits=12)),
                ('output_token_price_per_1m', models.DecimalField(decimal_places=8, max_digits=12)),
                ('cached_token_price_per_1m', models.DecimalField(decimal_places=8, max_digits=12)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'openai_ai_pricing',
                'indexes': [models.Index(fields=['model', 'effective_from'], name='ai_pricing_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('model', 'effective_from'), name='ai_pricing_model_from_uniq')],
            },
        ),
        migrations.CreateModel(
            name='AiUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(default='enrichment', max_length=32)),
                ('model', models.CharField(max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cached_tokens', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=12)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('langsmith_trace_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=10)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to='organisations.organisation')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='reviews.review')),
            ],
            options={
                'db_table': 'openai_ai_usage_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organisation', 'created_at'], name='ai_usage_org_created_idx'), models.Index(fields=['review'], name='ai_usage_review_idx'), models.Index(fields=['status'], name='ai_usage_status_idx')],
            },
        ),
    ]
