# Generated by Django 6.0.2 on 2026-04-27 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('region_id', models.CharField(db_index=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='organisations.organisation')),
            ],
            options={
                'db_table': 'regions_region',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['organisation', 'is_active'], name='region_org_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'region_id'), name='region_org_id_unique')],
            },
        ),
    ]
