# Generated by Django 6.0.2 on 2026-04-27 11:06

import django.db.models.deletion
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('street_address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('place_id', models.CharField(blank=True, db_index=True, max_length=300)),
                ('connection_method', models.CharField(choices=[('GOOGLE_OAUTH', 'Google OAuth'), ('MANUAL', 'Manual API Key'), ('NOT_CONNECTED', 'Not Connected')], db_index=True, default='NOT_CONNECTED', max_length=15)),
                ('connection_status', models.CharField(choices=[('CONNECTED', 'Connected'), ('EXPIRED', 'Connection Expired'), ('ERROR', 'Connection Error'), ('QUOTA_EXCEEDED', 'Quota Exceeded'), ('NOT_CONNECTED', 'Not Connected')], db_index=True, default='NOT_CONNECTED', max_length=15)),
                ('google_refresh_token', encrypted_fields.fields.EncryptedTextField(blank=True, default='', null=True)),
                ('api_key', encrypted_fields.fields.EncryptedTextField(blank=True, default='', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='organisations.organisation')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='regions.region')),
            ],
            options={
                'db_table': 'shops_shop',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organisation', 'is_active', 'connection_status'], name='shop_org_active_conn_idx')],
            },
        ),
    ]
