# Generated by Django 6.0.2 on 2026-04-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shopauditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='state',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='shop',
            name='connection_method',
            field=models.CharField(choices=[('GOOGLE_OAUTH', 'Google OAuth'), ('NOT_CONNECTED', 'Not Connected')], db_index=True, default='NOT_CONNECTED', max_length=15),
        ),
    ]
