# Generated by Django 6.0.2 on 2026-04-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('regions', '0001_initial'),
        ('shops', '0003_remove_manual_and_address_subfields'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.UniqueConstraint(condition=models.Q(('place_id__gt', '')), fields=('organisation', 'place_id'), name='shop_unique_place_id_per_org'),
        ),
    ]
