# Generated by Django 6.0.2 on 2026-05-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_unique_place_id_per_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='google_account_name',
            field=models.CharField(blank=True, default='', help_text='GBP API resource path, e.g. accounts/123', max_length=200),
        ),
        migrations.AddField(
            model_name='shop',
            name='google_location_name',
            field=models.CharField(blank=True, default='', help_text='GBP API resource path, e.g. accounts/123/locations/456', max_length=200),
        ),
    ]
