# Generated by Django 6.0.2 on 2026-05-10 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('shops', '0005_shop_google_account_name_shop_google_location_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_type', models.CharField(choices=[('WEEK', 'Weekly'), ('MONTH', 'Monthly')], db_index=True, max_length=5)),
                ('period_start', models.DateField(db_index=True)),
                ('target_count', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_targets', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_targets', to='organisations.organisation')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_targets', to='shops.shop')),
            ],
            options={
                'db_table': 'shops_reviewtarget',
                'ordering': ['period_start'],
                'indexes': [models.Index(fields=['organisation', 'shop', 'period_type', 'period_start'], name='target_org_shop_period_idx')],
                'constraints': [models.UniqueConstraint(fields=('shop', 'period_type', 'period_start'), name='target_unique_per_shop_period')],
            },
        ),
    ]
