# Generated by Django 6.0.2 on 2026-05-02 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_sequencecounter'),
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(db_index=True, max_length=50)),
                ('entity_id', models.CharField(db_index=True, max_length=200)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organisations.organisation')),
            ],
            options={
                'db_table': 'common_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organisation', 'entity_type', 'created_at'], name='audit_org_entity_date_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_entity_lookup_idx')],
            },
        ),
    ]
