# Generated by Django 6.0.2 on 2026-05-04 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        ('reviews', '0005_periodic_tasks_seed_retry_failed_enrichments'),
        ('shops', '0005_shop_google_account_name_shop_google_location_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('WONT_DO', "Won't Do")], db_index=True, default='TODO', max_length=15)),
                ('scope', models.CharField(choices=[('SHOP', 'Shop'), ('BRAND', 'Brand')], db_index=True, max_length=10)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('source', models.CharField(choices=[('AI', 'AI Extracted'), ('MANUAL', 'Manual')], db_index=True, default='MANUAL', max_length=10)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_action_items', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='organisations.organisation')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='shops.shop')),
                ('source_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='reviews.review')),
            ],
            options={
                'db_table': 'action_items_actionitem',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionItemNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=2000)),
                ('action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='action_items.actionitem')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'action_items_actionitemnote',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='actionitem',
            index=models.Index(fields=['organisation', 'status', 'scope'], name='ai_org_status_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='actionitem',
            index=models.Index(fields=['organisation', 'due_date'], name='ai_org_due_idx'),
        ),
        migrations.AddIndex(
            model_name='actionitem',
            index=models.Index(fields=['organisation', 'assignee'], name='ai_org_assignee_idx'),
        ),
        migrations.AddConstraint(
            model_name='actionitem',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'AI')), fields=('source_review', 'title', 'scope'), name='ai_unique_per_review_title_scope'),
        ),
    ]
