# Generated by Django 6.0.2 on 2026-05-15 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_items', '0001_initial'),
        ('organisations', '0001_initial'),
        ('reviews', '0007_replied_by_fk'),
        ('shops', '0007_recurring_review_targets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='category',
            field=models.CharField(choices=[('QUALITY', 'Quality'), ('SERVICE', 'Service'), ('EXPERIENCE', 'Experience'), ('OPERATIONS', 'Operations'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=15),
        ),
        migrations.AddIndex(
            model_name='actionitem',
            index=models.Index(fields=['organisation', 'category'], name='ai_org_category_idx'),
        ),
    ]
