# Generated by Django 6.0.2 on 2026-05-02 04:28

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        ('shops', '0005_shop_google_account_name_shop_google_location_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_review_id', models.CharField(db_index=True, max_length=200)),
                ('google_account_id', models.CharField(blank=True, max_length=200)),
                ('google_location_id', models.CharField(blank=True, max_length=200)),
                ('star_rating', models.SmallIntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], db_index=True)),
                ('reviewer_display_name', models.CharField(blank=True, max_length=300)),
                ('reviewer_photo_url', models.URLField(blank=True, max_length=500)),
                ('reviewer_is_anonymous', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('review_create_time', models.DateTimeField(db_index=True)),
                ('review_update_time', models.DateTimeField()),
                ('reply_comment', models.TextField(blank=True)),
                ('reply_update_time', models.DateTimeField(blank=True, null=True)),
                ('is_replied', models.BooleanField(db_index=True, default=False)),
                ('enrichment_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=15)),
                ('enrichment_version', models.PositiveSmallIntegerField(default=0)),
                ('enrichment_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='organisations.organisation')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shops.shop')),
            ],
            options={
                'db_table': 'reviews_review',
                'ordering': ['-review_create_time'],
                'indexes': [models.Index(fields=['organisation', 'shop', 'is_replied', 'star_rating'], name='review_org_shop_filter_idx'), models.Index(fields=['organisation', 'review_create_time'], name='review_org_date_idx'), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='review_search_vec_idx')],
                'constraints': [models.UniqueConstraint(fields=('shop', 'google_review_id'), name='review_unique_per_shop')],
            },
        ),
    ]
