# Generated by Django 6.0.2 on 2026-05-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_periodic_tasks_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
