# Generated by Django 6.0.2 on 2026-05-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='extracted_action_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
