# Generated by Django 6.0.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0007_replied_by_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="reviews.review",
                    ),
                ),
                ("label", models.CharField(db_index=True, max_length=100)),
                (
                    "polarity",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={"db_table": "reviews_reviewtag"},
        ),
        migrations.AddIndex(
            model_name="reviewtag",
            index=models.Index(
                fields=["review", "label"], name="reviewtag_review_label_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="review",
            name="tags",
        ),
    ]
