# Generated by Django 6.0.2 on 2026-05-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_reviewtag'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reviewtag',
            constraint=models.UniqueConstraint(fields=('review', 'label', 'polarity'), name='uniq_reviewtag_review_label_polarity'),
        ),
    ]
