# Generated by Django 6.0.2 on 2026-06-10 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisation_allow_custom_sync_depth'),
        ('reviews', '0010_add_enrichment_error_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgCanonicalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100)),
                ('polarity_type', models.CharField(choices=[('always_positive', 'Always Positive'), ('always_negative', 'Always Negative'), ('mixed', 'Mixed')], max_length=20)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_tags', to='organisations.organisation')),
            ],
            options={
                'db_table': 'reviews_orgcanonicaltag',
            },
        ),
        migrations.AddField(
            model_name='reviewtag',
            name='canonical_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_tags', to='reviews.orgcanonicaltag'),
        ),
        migrations.AddIndex(
            model_name='orgcanonicaltag',
            index=models.Index(fields=['organisation', '-review_count'], name='orgcanon_org_count_idx'),
        ),
        migrations.AddConstraint(
            model_name='orgcanonicaltag',
            constraint=models.UniqueConstraint(fields=('organisation', 'label'), name='uniq_orgcanonicaltag_org_label'),
        ),
    ]
