# Generated by Django 6.0.2 on 2026-06-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_orgcanonicaltag_reviewtag_canonical_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgcanonicaltag',
            name='polarity_reclassified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
