# Generated by Django 6.0.2 on 2026-06-16 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisation_allow_custom_sync_depth'),
        ('reviews', '0013_periodic_task_seed_polarity_reclassify'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagMergeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_label', models.CharField(max_length=100)),
                ('target_label', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('dismissed', models.BooleanField(db_index=True, default=False)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_merge_jobs', to='organisations.organisation')),
                ('source_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reviews.orgcanonicaltag')),
                ('target_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reviews.orgcanonicaltag')),
            ],
            options={
                'indexes': [models.Index(fields=['organisation', 'status'], name='tagmergejob_org_status_idx'), models.Index(fields=['organisation', '-created_at'], name='tagmergejob_org_date_idx')],
            },
        ),
    ]
