# Generated by Django 6.0.2 on 2026-04-22 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('org_type', models.CharField(choices=[('RETAIL', 'Retail'), ('RESTAURANT', 'Restaurant'), ('PHARMACY', 'Pharmacy'), ('SUPERMARKET', 'Supermarket')], db_index=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(blank=True, max_length=500)),
                ('number_of_stores', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled'), ('DELETED', 'Deleted')], db_index=True, default='ACTIVE', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organisations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organisations_organisation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='org_status_created_idx'), models.Index(fields=['org_type', 'status'], name='org_type_status_idx')],
            },
        ),
    ]
