# Generated by Django 6.0.2 on 2026-05-04 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('action_items', '0001_initial'),
        ('organisations', '0001_initial'),
        ('reviews', '0005_periodic_tasks_seed_retry_failed_enrichments'),
        ('shops', '0005_shop_google_account_name_shop_google_location_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('new_review', 'New Review'), ('new_action_item', 'New Action Item'), ('action_item_assigned', 'Action Item Assigned')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('target_url', models.CharField(max_length=500)),
                ('action_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='action_items.actionitem')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='organisations.organisation')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.review')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.shop')),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='notif_recipient_unread_idx')],
            },
        ),
    ]
