# Generated by Django 6.0.2 on 2026-06-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_review', 'New Review'), ('new_action_item', 'New Action Item'), ('action_item_assigned', 'Action Item Assigned'), ('tag_merge_complete', 'Tag Merge Complete')], db_index=True, max_length=30),
        ),
    ]
